### PR TITLE
chore: allow more google tracking

### PR DESCRIPTION
**Pull request by lazysoundsystem**
Refs: OPS-10398
OPS-10457

Note that this removes 'unsafe-eval', which I don't think we need. We should wait to merge this until we're sure we need the ad services, doubleclick, etc domains.

### CODE REVIEW

**Comment by lazysoundsystem** [comment]
All of the google domains would have to be added for img-src too if we didn't have
the permissive `https://*` - wondering if that would be acceptable for
`connect-src` too - otherwise this is a very ugly header to send with
every request.

Also, presumably google updates their domain list every so often, so this list will go out of date.

**Review by orakili — APPROVED** [review]
Ouch, that's kind of insane.

**Comment by lazysoundsystem** [comment]
Yes! what do you think of using `https://*` for connect-src too? If our xss protections are working correctly, it should be okay, shouldn't it?

**Comment by orakili** [comment]
`https://*` is fine with me. It's slightly better than without the CSP.

**Review by orakili — APPROVED** [review]
Tested on `demo` and this seems to work.

**Comment by lazysoundsystem** [comment]
Looks good to me too on demo. Merging.

**Pull request merged**
