### PR TITLE
chore: use GHA to run tests

### PR DESCRIPTION
**Pull request by lazysoundsystem**
Refs: OPS-9006

I understand these haven't been included yet as the tests take longer to run than the travis ones - so this branch doesn't need to be merged while we have Travis (i.e. November 2023) - but pushing it as it's up-to-date with the tests for the other repos - and any adjustments for speed would probably benefit the other repos too.

### CODE REVIEW

**Comment by lazysoundsystem** [comment]
There's now a PR to remove the blocker: https://github.com/UN-OCHA/rwint9-site/pull/605

**Comment by lazysoundsystem** [comment]
The tests are passing now - but it shows the Travis tests taking 5 minutes and the GHA tests taking 9 minutes. Will look later to see if anything can be speeded up.

**Comment by orakili** [comment]
For reference: https://humanitarian.atlassian.net/browse/RW-748. I had the same issue with GHA in https://github.com/UN-OCHA/rwint9-site/pull/571 which is why it was not merged.

**Comment by orakili** [comment]
Closing in favor of https://github.com/UN-OCHA/rwint9-site/pull/571.

**Pull request closed without merging**
