### PR TITLE
[RW-21] User revisions - DO NOT MERGE YET

### PR DESCRIPTION
**Pull request by orakili**
Refs: RW-21

This adds the user_revision module (MR3 of https://www.drupal.org/project/user_revision/issues/3197068) and adjusts the reliefweb_revisions module to be more flexible and do not assume all revisioned entities are also moderated ones.

### Tests

1. Checkout this branch and run `composer install` to install the user_revision
2. Run `drush cr` then `drush cim`, this should enable the user_revision module and start a batch to make the user entities revisionable (can take several minutes)
3. Log in with a an existing "normal" user, change the display name or email address
4. Log in with an account with the "User Manager" role, edit the account from (3), there should be the revision history at the bottom of the form showing the change of display name/email address
5. Change something for the account (3), leave a revision comment, save and edit again to confirm the changes and check they also appear in the revision history with the comment

**Important:** This makes changes to the DB so either backup your DB before reviewing this PR or import a fresh dump when done with the review and checking out another branch.

### CODE REVIEW

**Review by left23 — APPROVED** [review]
Works as described

**Review by lazysoundsystem — APPROVED** [review]
For me too, all works as described.

**Comment by attiks** [comment]
https://www.drupal.org/project/user_revision/issues/3197068 is merged

**Comment by attiks** [comment]
Follow-up opened to get a stable version, https://www.drupal.org/project/user_revision/issues/3303678

**Comment by orakili** [comment]
Closed in favor of https://github.com/UN-OCHA/rwint9-site/pull/543

**Pull request closed without merging**
