### PR TITLE
chore: add mail modules

### PR DESCRIPTION
**Pull request by lazysoundsystem**
Refs: OPS-9523

### CODE REVIEW

**Comment by lazysoundsystem** [comment]
@orakili this adds the amazon_ses module without enabling or configuring it, in preparation for those two steps. As suggested in https://github.com/UN-OCHA/unocha-site/pull/421 - it may be worth merging now to avoid further conflicts with this week's periodic updates.

**Comment by lazysoundsystem** [comment]
Note - adjusted the threshold for test coverage from 10% to 8% so that the checks can pass.

**Comment by cafuego** [comment]
RW doesn't use the Drupal mail() function to send its subscription mails, does it?

**Review by cafuego — CHANGES_REQUESTED** [review]
I'm going to need to drop in some extra changes.

**Comment by orakili** [comment]
Closing in favor of https://github.com/UN-OCHA/rwint9-site/pull/773.

**Pull request closed without merging**
